version: '3.8'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    environment:
      - WORKER_URL=http://worker1:3001 # Update this to the correct URL and port
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=farm1
    ports:
      - '3000:3000'
    networks:
      - app-network

  worker1:
    build:
      context: ./worker1
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=farm1
    ports:
      - '3001:3001'
    networks:
      - app-network

  blob:
    build:
      context: ./blob
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=farm1
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15672:15672" # RabbitMQ management UI
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: farm1
    ports:
      - "5432:5432"
    networks:
      - app-network

  liquibase:
    build:
      context: ./liquibase
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=farm1
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
